import type { SourceMetadata } from '@/types/trust';

// Source allowlist — only sources in this registry are queried.
// New providers must be added here with trust classification before use.
export const TRUSTED_SOURCES: SourceMetadata[] = [
  // Israeli carriers — official
  {
    id: 'elal',
    name: 'El Al',
    domain: 'elal.com',
    trustLevel: 'official',
    type: 'airline',
    country: 'IL',
    isActive: true,
    isOfficial: true,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'arkia',
    name: 'Arkia',
    domain: 'arkia.com',
    trustLevel: 'official',
    type: 'airline',
    country: 'IL',
    isActive: true,
    isOfficial: true,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'israir',
    name: 'Israir',
    domain: 'israirairlines.com',
    trustLevel: 'official',
    type: 'airline',
    country: 'IL',
    isActive: true,
    isOfficial: true,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
  // European LCCs
  {
    id: 'ryanair',
    name: 'Ryanair',
    domain: 'ryanair.com',
    trustLevel: 'official',
    type: 'airline',
    country: 'IE',
    isActive: true,
    isOfficial: true,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'easyjet',
    name: 'easyJet',
    domain: 'easyjet.com',
    trustLevel: 'official',
    type: 'airline',
    country: 'GB',
    isActive: true,
    isOfficial: true,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'wizz',
    name: 'Wizz Air',
    domain: 'wizzair.com',
    trustLevel: 'official',
    type: 'airline',
    country: 'HU',
    isActive: true,
    isOfficial: true,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
  // Full-service carriers
  {
    id: 'british_airways',
    name: 'British Airways',
    domain: 'britishairways.com',
    trustLevel: 'official',
    type: 'airline',
    country: 'GB',
    isActive: true,
    isOfficial: true,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'lufthansa',
    name: 'Lufthansa',
    domain: 'lufthansa.com',
    trustLevel: 'official',
    type: 'airline',
    country: 'DE',
    isActive: true,
    isOfficial: true,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'air_france',
    name: 'Air France',
    domain: 'airfrance.com',
    trustLevel: 'official',
    type: 'airline',
    country: 'FR',
    isActive: true,
    isOfficial: true,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'turkish',
    name: 'Turkish Airlines',
    domain: 'turkishairlines.com',
    trustLevel: 'official',
    type: 'airline',
    country: 'TR',
    isActive: true,
    isOfficial: true,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
  // Duffel GDS — multi-airline (300+ carriers, free signup at app.duffel.com)
  {
    id: 'duffel',
    name: 'Duffel (Multi-Airline)',
    domain: 'duffel.com',
    trustLevel: 'trusted_partner',
    type: 'airline',
    country: 'GB',
    isActive: true,
    isOfficial: false,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
  // Mock / fallback providers — always trusted (internal, never blocked)
  {
    id: 'mock_flights',
    name: 'Sample Flights',
    domain: 'localhost',
    trustLevel: 'trusted_partner',
    type: 'airline',
    country: 'IL',
    isActive: true,
    isOfficial: false,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'mock_hotels',
    name: 'Sample Hotels',
    domain: 'localhost',
    trustLevel: 'trusted_partner',
    type: 'hotel',
    country: 'IL',
    isActive: true,
    isOfficial: false,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
  // Hotel sources
  {
    id: 'booking_com',
    name: 'Booking.com',
    domain: 'booking.com',
    trustLevel: 'trusted_partner',
    type: 'hotel',
    country: 'NL',
    isActive: true,
    isOfficial: false,
    addedAt: '2024-01-01T00:00:00.000Z',
  },
];

// Explicit blocklist — domains that must never be queried
export const BLOCKED_DOMAINS: string[] = [
  'cheapfakeflights.com',
  'skyscam.net',
];
